#!/usr/bin/env bash
# Write .env.local for each Next.js surface (Next.js only loads env from app dirs).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [ -f "$ROOT/.env" ]; then set -a; source "$ROOT/.env"; set +a; fi

GW="${API_GATEWAY_URL:-http://localhost:3000}"
STAFF_SECRET="${STAFF_SESSION_SECRET:-aurixa-local-staff-session-secret-32b}"
CLIENT_SECRET="${CLIENT_SESSION_SECRET:-aurixa-local-client-session-secret-32}"
AUTH_SECRET="${AUTH_SECRET:-aurixa-local-development-auth-secret-32}"

cat >"$ROOT/frontend/agent-workspace/.env.local" <<EOF
# Generated by scripts/sync-frontend-env.sh — do not commit
NODE_ENV=development
API_GATEWAY_URL=$GW
NEXT_PUBLIC_API_GATEWAY_URL=http://localhost:3000
STAFF_DEMO_AUTH_ENABLED=true
STAFF_DEMO_STAFF_ID=${STAFF_DEMO_STAFF_ID:-1}
STAFF_DEMO_TENANT_ID=${STAFF_DEMO_TENANT_ID:-1}
STAFF_DEMO_FULL_NAME="${STAFF_DEMO_FULL_NAME:-Demo Agent}"
STAFF_DEMO_EMAIL=${STAFF_DEMO_EMAIL:-demo-agent@localhost}
STAFF_DEMO_ROLE=${STAFF_DEMO_ROLE:-agent}
STAFF_SESSION_SECRET=$STAFF_SECRET
EOF

cat >"$ROOT/frontend/client-portal/.env.local" <<EOF
# Generated by scripts/sync-frontend-env.sh — do not commit
NODE_ENV=development
API_GATEWAY_URL=$GW
NEXT_PUBLIC_API_GATEWAY_URL=http://localhost:3000
CLIENT_DEMO_AUTH_ENABLED=true
CLIENT_DEMO_CLIENT_ID=${CLIENT_DEMO_CLIENT_ID:-1}
CLIENT_DEMO_TENANT_ID=${CLIENT_DEMO_TENANT_ID:-1}
CLIENT_SESSION_SECRET=$CLIENT_SECRET
EOF

cat >"$ROOT/frontend/dashboard/.env.local" <<EOF
# Generated by scripts/sync-frontend-env.sh — do not commit
NODE_ENV=development
NEXT_PUBLIC_API_GATEWAY_URL=http://localhost:3000
DEPLOYMENT_GATEWAY_URL=http://localhost:3000/api/v1/admin/deployments
AUTH_SECRET=$AUTH_SECRET
NEXTAUTH_URL=http://localhost:3100
DEPLOYMENT_DEV_AUTH_ENABLED=true
EOF

echo "Synced .env.local for agent-workspace, client-portal, and dashboard."
