"""Seed record definitions — ~60% US / ~40% India mix."""

from __future__ import annotations

from typing import Any

# --- Tenants (4 US + 2 IN) ---------------------------------------------------

US_TENANTS: list[dict[str, Any]] = [
    {
        "name": "Harbor Realty Group",
        "domain": "harborrealty.com",
        "org_type": "brokerage",
        "plan": "enterprise",
        "api_key_count": 5,
    },
    {
        "name": "Urban Living PM",
        "domain": "urbanlivingpm.com",
        "org_type": "pm",
        "plan": "professional",
        "api_key_count": 3,
    },
    {
        "name": "Summit Homes Development",
        "domain": "summithomes.dev",
        "org_type": "developer",
        "plan": "enterprise",
        "api_key_count": 4,
    },
    {
        "name": "Lakeview Brokers",
        "domain": "lakeviewbrokers.com",
        "org_type": "brokerage",
        "plan": "starter",
        "api_key_count": 1,
    },
]

IN_TENANTS: list[dict[str, Any]] = [
    {
        "name": "Bengaluru Prime Realty",
        "domain": "bengaluruprime.in",
        "org_type": "brokerage",
        "plan": "professional",
        "api_key_count": 3,
    },
    {
        "name": "Mumbai Urban Living",
        "domain": "mumbaiurbanliving.in",
        "org_type": "pm",
        "plan": "professional",
        "api_key_count": 2,
    },
]

# --- Staff -------------------------------------------------------------------

US_STAFF: list[dict[str, Any]] = [
    {"full_name": "Alex Rivera", "email": "alex.rivera@harborrealty.com", "role": "agent", "tenant_index": 0},
    {"full_name": "Jordan Lee", "email": "jordan.lee@harborrealty.com", "role": "broker", "tenant_index": 0},
    {"full_name": "Sam Ortiz", "email": "sam.ortiz@harborrealty.com", "role": "showing_coordinator", "tenant_index": 0},
    {"full_name": "Harbor Admin", "email": "admin@harborrealty.com", "role": "admin", "tenant_index": 0},
    {"full_name": "Morgan Chen", "email": "morgan.chen@urbanlivingpm.com", "role": "leasing_coordinator", "tenant_index": 1},
    {"full_name": "Riley Park", "email": "riley.park@urbanlivingpm.com", "role": "property_manager", "tenant_index": 1},
    {"full_name": "Casey Brooks", "email": "casey.brooks@summithomes.dev", "role": "agent", "tenant_index": 2},
    {"full_name": "Taylor Walsh", "email": "taylor.walsh@lakeviewbrokers.com", "role": "agent", "tenant_index": 3},
]

IN_STAFF: list[dict[str, Any]] = [
    {"full_name": "Priya Sharma", "email": "priya.sharma@bengaluruprime.in", "role": "agent", "tenant_index": 4},
    {"full_name": "Arjun Mehta", "email": "arjun.mehta@bengaluruprime.in", "role": "broker", "tenant_index": 4},
    {"full_name": "Kavitha Nair", "email": "kavitha.nair@mumbaiurbanliving.in", "role": "leasing_coordinator", "tenant_index": 5},
    {"full_name": "Rahul Desai", "email": "rahul.desai@mumbaiurbanliving.in", "role": "property_manager", "tenant_index": 5},
]

# --- Clients (12 US + 8 IN) — Jane Smith must remain index 0 -----------------

US_CLIENTS: list[dict[str, Any]] = [
    {
        "full_name": "Jane Smith",
        "email": "jane.smith@email.com",
        "phone_number": "+1-503-555-0101",
        "client_type": "buyer",
        "tenant_index": 0,
        "preferences": {"areas": ["Downtown", "Westside"], "budget_max": 500000, "beds_min": 3},
    },
    {
        "full_name": "Michael Torres",
        "email": "m.torres@email.com",
        "phone_number": "+1-503-555-0102",
        "client_type": "buyer",
        "tenant_index": 0,
        "preferences": {"areas": ["Suburbs", "Beaverton"], "budget_max": 650000, "beds_min": 4},
    },
    {
        "full_name": "Emily Nguyen",
        "email": "emily.nguyen@email.com",
        "phone_number": "+1-503-555-0103",
        "client_type": "renter",
        "tenant_index": 1,
        "preferences": {"beds_min": 2, "pets": True},
    },
    {
        "full_name": "David Kim",
        "email": "david.kim@email.com",
        "phone_number": "+1-512-555-0144",
        "client_type": "seller",
        "tenant_index": 0,
    },
    {
        "full_name": "Sarah Patel",
        "email": "sarah.patel@email.com",
        "phone_number": "+1-503-555-0104",
        "client_type": "buyer",
        "tenant_index": 2,
        "preferences": {"budget_max": 800000, "beds_min": 4},
    },
    {
        "full_name": "Chris Anderson",
        "email": "chris.anderson@email.com",
        "phone_number": "+1-206-555-0188",
        "client_type": "buyer",
        "tenant_index": 0,
        "preferences": {"areas": ["Capitol Hill", "Queen Anne"], "budget_max": 720000, "beds_min": 2},
    },
    {
        "full_name": "Olivia Martinez",
        "email": "olivia.martinez@email.com",
        "phone_number": "+1-303-555-0177",
        "client_type": "buyer",
        "tenant_index": 3,
        "preferences": {"areas": ["LoDo", "RiNo"], "budget_max": 550000, "beds_min": 2},
    },
    {
        "full_name": "James Wilson",
        "email": "james.wilson@email.com",
        "phone_number": "+1-704-555-0166",
        "client_type": "renter",
        "tenant_index": 1,
        "preferences": {"beds_min": 3, "areas": ["South End"]},
    },
    {
        "full_name": "Ashley Brown",
        "email": "ashley.brown@email.com",
        "phone_number": "+1-512-555-0199",
        "client_type": "buyer",
        "tenant_index": 0,
        "preferences": {"areas": ["East Austin", "Mueller"], "budget_max": 620000, "beds_min": 3},
    },
    {
        "full_name": "Robert Chen",
        "email": "robert.chen@email.com",
        "phone_number": "+1-206-555-0122",
        "client_type": "seller",
        "tenant_index": 3,
    },
    {
        "full_name": "Megan Foster",
        "email": "megan.foster@email.com",
        "phone_number": "+1-303-555-0133",
        "client_type": "buyer",
        "tenant_index": 3,
        "preferences": {"budget_max": 480000, "beds_min": 3, "areas": ["Highlands"]},
    },
    {
        "full_name": "Daniel Hughes",
        "email": "daniel.hughes@email.com",
        "phone_number": "+1-704-555-0155",
        "client_type": "buyer",
        "tenant_index": 0,
        "preferences": {"areas": ["Uptown", "Dilworth"], "budget_max": 590000, "beds_min": 3},
    },
]

IN_CLIENTS: list[dict[str, Any]] = [
    {
        "full_name": "Ananya Iyer",
        "email": "ananya.iyer@gmail.com",
        "phone_number": "+91-98765-43210",
        "client_type": "buyer",
        "tenant_index": 4,
        "preferences": {"areas": ["Koramangala", "HSR Layout"], "budget_max": 15000000, "beds_min": 3},
    },
    {
        "full_name": "Vikram Reddy",
        "email": "vikram.reddy@gmail.com",
        "phone_number": "+91-98450-12345",
        "client_type": "buyer",
        "tenant_index": 4,
        "preferences": {"areas": ["Whitefield", "Indiranagar"], "budget_max": 22000000, "beds_min": 3},
    },
    {
        "full_name": "Neha Kapoor",
        "email": "neha.kapoor@gmail.com",
        "phone_number": "+91-98200-55667",
        "client_type": "renter",
        "tenant_index": 5,
        "preferences": {"beds_min": 2, "areas": ["Bandra West", "Powai"], "pets": False},
    },
    {
        "full_name": "Rohan Malhotra",
        "email": "rohan.malhotra@gmail.com",
        "phone_number": "+91-98190-77889",
        "client_type": "buyer",
        "tenant_index": 4,
        "preferences": {"areas": ["Golf Course Road", "Sector 57"], "budget_max": 35000000, "beds_min": 4},
    },
    {
        "full_name": "Priya Menon",
        "email": "priya.menon@gmail.com",
        "phone_number": "+91-98940-33445",
        "client_type": "renter",
        "tenant_index": 5,
        "preferences": {"beds_min": 1, "areas": ["Andheri East", "Goregaon"]},
    },
    {
        "full_name": "Aditya Joshi",
        "email": "aditya.joshi@gmail.com",
        "phone_number": "+91-99887-66554",
        "client_type": "buyer",
        "tenant_index": 4,
        "preferences": {"areas": ["Hitech City", "Gachibowli"], "budget_max": 18000000, "beds_min": 3},
    },
    {
        "full_name": "Sneha Pillai",
        "email": "sneha.pillai@gmail.com",
        "phone_number": "+91-97654-32109",
        "client_type": "buyer",
        "tenant_index": 5,
        "preferences": {"areas": ["Koregaon Park", "Kalyani Nagar"], "budget_max": 12000000, "beds_min": 2},
    },
    {
        "full_name": "Karthik Srinivasan",
        "email": "karthik.s@gmail.com",
        "phone_number": "+91-99000-11223",
        "client_type": "seller",
        "tenant_index": 4,
    },
]

# --- Properties (12 US + 8 IN) — index 0 = demo Oak Street -------------------

US_PROPERTIES: list[dict[str, Any]] = [
    {
        "tenant_index": 0,
        "address_line1": "123 Oak Street",
        "city": "Portland",
        "state": "OR",
        "postal_code": "97201",
        "property_type": "single_family",
        "beds": 3,
        "baths": 2.0,
        "sqft": 1850,
        "year_built": 1998,
    },
    {
        "tenant_index": 0,
        "address_line1": "456 Maple Avenue",
        "city": "Portland",
        "state": "OR",
        "postal_code": "97209",
        "property_type": "townhouse",
        "beds": 4,
        "baths": 2.5,
        "sqft": 2100,
        "year_built": 2015,
    },
    {
        "tenant_index": 1,
        "address_line1": "789 River View #204",
        "city": "Portland",
        "state": "OR",
        "postal_code": "97204",
        "property_type": "condo",
        "beds": 2,
        "baths": 2.0,
        "sqft": 1100,
        "year_built": 2018,
    },
    {
        "tenant_index": 2,
        "address_line1": "12 Summit Ridge Lane",
        "city": "Beaverton",
        "state": "OR",
        "postal_code": "97005",
        "property_type": "single_family",
        "beds": 4,
        "baths": 3.0,
        "sqft": 2450,
        "year_built": 2024,
    },
    {
        "tenant_index": 0,
        "address_line1": "2201 East 6th Street",
        "city": "Austin",
        "state": "TX",
        "postal_code": "78702",
        "property_type": "single_family",
        "beds": 3,
        "baths": 2.0,
        "sqft": 1680,
        "year_built": 2005,
    },
    {
        "tenant_index": 0,
        "address_line1": "1420 Pike Place #1802",
        "city": "Seattle",
        "state": "WA",
        "postal_code": "98101",
        "property_type": "condo",
        "beds": 2,
        "baths": 2.0,
        "sqft": 980,
        "year_built": 2019,
    },
    {
        "tenant_index": 3,
        "address_line1": "1842 Blake Street",
        "city": "Denver",
        "state": "CO",
        "postal_code": "80202",
        "property_type": "townhouse",
        "beds": 3,
        "baths": 2.5,
        "sqft": 1750,
        "year_built": 2012,
    },
    {
        "tenant_index": 3,
        "address_line1": "501 South Tryon Street #1204",
        "city": "Charlotte",
        "state": "NC",
        "postal_code": "28202",
        "property_type": "condo",
        "beds": 2,
        "baths": 2.0,
        "sqft": 1150,
        "year_built": 2020,
    },
    {
        "tenant_index": 1,
        "address_line1": "3100 Pearl Parkway #512",
        "city": "Austin",
        "state": "TX",
        "postal_code": "78759",
        "property_type": "apartment",
        "beds": 2,
        "baths": 2.0,
        "sqft": 1050,
        "year_built": 2021,
    },
    {
        "tenant_index": 0,
        "address_line1": "8800 NE Vancouver Mall Drive",
        "city": "Vancouver",
        "state": "WA",
        "postal_code": "98662",
        "property_type": "townhouse",
        "beds": 4,
        "baths": 3.0,
        "sqft": 2200,
        "year_built": 2017,
    },
    {
        "tenant_index": 2,
        "address_line1": "9100 N Lamar Boulevard",
        "city": "Austin",
        "state": "TX",
        "postal_code": "78753",
        "property_type": "single_family",
        "beds": 4,
        "baths": 3.0,
        "sqft": 2380,
        "year_built": 2023,
    },
    {
        "tenant_index": 1,
        "address_line1": "1600 Glenarm Place #904",
        "city": "Denver",
        "state": "CO",
        "postal_code": "80202",
        "property_type": "condo",
        "beds": 1,
        "baths": 1.0,
        "sqft": 720,
        "year_built": 2016,
    },
]

IN_PROPERTIES: list[dict[str, Any]] = [
    {
        "tenant_index": 4,
        "address_line1": "42 12th Main Road, Koramangala 4th Block",
        "city": "Bengaluru",
        "state": "KA",
        "postal_code": "560034",
        "property_type": "apartment",
        "beds": 3,
        "baths": 2.0,
        "sqft": 1450,
        "year_built": 2018,
    },
    {
        "tenant_index": 4,
        "address_line1": "Plot 17, Whitefield Main Road",
        "city": "Bengaluru",
        "state": "KA",
        "postal_code": "560066",
        "property_type": "villa",
        "beds": 4,
        "baths": 4.0,
        "sqft": 2800,
        "year_built": 2021,
    },
    {
        "tenant_index": 5,
        "address_line1": "Flat 1203, Lodha Park, Lower Parel",
        "city": "Mumbai",
        "state": "MH",
        "postal_code": "400013",
        "property_type": "apartment",
        "beds": 2,
        "baths": 2.0,
        "sqft": 1100,
        "year_built": 2019,
    },
    {
        "tenant_index": 5,
        "address_line1": "B-902, Hiranandani Gardens, Powai",
        "city": "Mumbai",
        "state": "MH",
        "postal_code": "400076",
        "property_type": "apartment",
        "beds": 3,
        "baths": 2.5,
        "sqft": 1350,
        "year_built": 2017,
    },
    {
        "tenant_index": 4,
        "address_line1": "Tower C, DLF Phase 2, Sector 25",
        "city": "Gurugram",
        "state": "HR",
        "postal_code": "122002",
        "property_type": "apartment",
        "beds": 4,
        "baths": 4.0,
        "sqft": 2650,
        "year_built": 2020,
    },
    {
        "tenant_index": 4,
        "address_line1": "88 Road No. 36, Jubilee Hills",
        "city": "Hyderabad",
        "state": "TS",
        "postal_code": "500033",
        "property_type": "single_family",
        "beds": 3,
        "baths": 3.0,
        "sqft": 2100,
        "year_built": 2016,
    },
    {
        "tenant_index": 5,
        "address_line1": "14 North Main Road, Koregaon Park",
        "city": "Pune",
        "state": "MH",
        "postal_code": "411001",
        "property_type": "apartment",
        "beds": 2,
        "baths": 2.0,
        "sqft": 980,
        "year_built": 2015,
    },
    {
        "tenant_index": 4,
        "address_line1": "HSR Layout Sector 2, 27th Cross",
        "city": "Bengaluru",
        "state": "KA",
        "postal_code": "560102",
        "property_type": "apartment",
        "beds": 2,
        "baths": 2.0,
        "sqft": 1180,
        "year_built": 2019,
    },
]

# property_index references combined US+IN property list (US first)
US_LISTINGS: list[dict[str, Any]] = [
    {
        "property_index": 0,
        "tenant_index": 0,
        "listing_type": "sale",
        "status": "active",
        "list_price": 485000,
        "marketing_title": "Charming 3BR Craftsman near parks",
        "marketing_description": "Updated kitchen, fenced yard, walkable Westside neighborhood.",
        "days_published": 14,
    },
    {
        "property_index": 1,
        "tenant_index": 0,
        "listing_type": "sale",
        "status": "active",
        "list_price": 625000,
        "marketing_title": "Modern townhouse with garage",
        "marketing_description": "Open floor plan, primary suite, low HOA in Downtown Portland.",
        "days_published": 7,
    },
    {
        "property_index": 2,
        "tenant_index": 1,
        "listing_type": "rent",
        "status": "active",
        "rent_amount": 2400,
        "marketing_title": "2BR river-view condo",
        "marketing_description": "Pet-friendly building with gym and rooftop deck.",
        "days_published": 3,
    },
    {
        "property_index": 3,
        "tenant_index": 2,
        "listing_type": "sale",
        "status": "active",
        "list_price": 789000,
        "marketing_title": "New construction at Summit Ridge",
        "marketing_description": "Model home now open — energy-efficient build with smart home package.",
        "days_published": 1,
    },
    {
        "property_index": 4,
        "tenant_index": 0,
        "listing_type": "sale",
        "status": "active",
        "list_price": 595000,
        "marketing_title": "East Austin bungalow with studio",
        "marketing_description": "Walk to coffee shops, updated electrical, large backyard.",
        "days_published": 10,
    },
    {
        "property_index": 5,
        "tenant_index": 0,
        "listing_type": "sale",
        "status": "active",
        "list_price": 715000,
        "marketing_title": "Pike Place condo with Puget Sound views",
        "marketing_description": "Capitol Hill adjacent, concierge building, two parking stalls.",
        "days_published": 5,
    },
    {
        "property_index": 6,
        "tenant_index": 3,
        "listing_type": "sale",
        "status": "active",
        "list_price": 520000,
        "marketing_title": "RiNo-adjacent Denver townhouse",
        "marketing_description": "Rooftop deck, LoDo commute, newer mechanicals.",
        "days_published": 8,
    },
    {
        "property_index": 7,
        "tenant_index": 3,
        "listing_type": "sale",
        "status": "active",
        "list_price": 410000,
        "marketing_title": "Uptown Charlotte high-rise unit",
        "marketing_description": "Floor-to-ceiling windows, pool, walking distance to light rail.",
        "days_published": 12,
    },
    {
        "property_index": 8,
        "tenant_index": 1,
        "listing_type": "rent",
        "status": "active",
        "rent_amount": 2100,
        "marketing_title": "Pearl District Austin rental",
        "marketing_description": "In-unit laundry, pool, close to Domain employers.",
        "days_published": 4,
    },
    {
        "property_index": 9,
        "tenant_index": 0,
        "listing_type": "sale",
        "status": "pending",
        "list_price": 680000,
        "marketing_title": "Vancouver WA family home",
        "marketing_description": "Suburbs layout, three-car garage, offer review weekend.",
        "days_published": 20,
    },
    {
        "property_index": 10,
        "tenant_index": 2,
        "listing_type": "sale",
        "status": "active",
        "list_price": 545000,
        "marketing_title": "North Austin new-build spec",
        "marketing_description": "Builder incentives available through month end.",
        "days_published": 2,
    },
    {
        "property_index": 11,
        "tenant_index": 1,
        "listing_type": "rent",
        "status": "active",
        "rent_amount": 1850,
        "marketing_title": "Downtown Denver studio rental",
        "marketing_description": "Furnished option, utilities included, 6-month lease ok.",
        "days_published": 6,
    },
]

IN_LISTINGS: list[dict[str, Any]] = [
    {
        "property_index": 12,
        "tenant_index": 4,
        "listing_type": "sale",
        "status": "active",
        "list_price": 12500000,
        "marketing_title": "3BHK Koramangala corner flat",
        "marketing_description": "RERA registered, club house, 2 covered parking. Price in INR.",
        "days_published": 9,
    },
    {
        "property_index": 13,
        "tenant_index": 4,
        "listing_type": "sale",
        "status": "active",
        "list_price": 28500000,
        "marketing_title": "Whitefield gated villa",
        "marketing_description": "Private garden, solar backup, near ITPL corridor.",
        "days_published": 4,
    },
    {
        "property_index": 14,
        "tenant_index": 5,
        "listing_type": "rent",
        "status": "active",
        "rent_amount": 95000,
        "marketing_title": "Lower Parel 2BHK with sea glimpse",
        "marketing_description": "Full society amenities, no brokerage, family preferred.",
        "days_published": 2,
    },
    {
        "property_index": 15,
        "tenant_index": 5,
        "listing_type": "rent",
        "status": "active",
        "rent_amount": 85000,
        "marketing_title": "Powai lake-view 3BHK",
        "marketing_description": "Hiranandani estate, maid room, immediate possession.",
        "days_published": 5,
    },
    {
        "property_index": 16,
        "tenant_index": 4,
        "listing_type": "sale",
        "status": "active",
        "list_price": 42000000,
        "marketing_title": "Gurugram Golf Course Road 4BHK",
        "marketing_description": "Premium tower, concierge, close to metro and schools.",
        "days_published": 11,
    },
    {
        "property_index": 17,
        "tenant_index": 4,
        "listing_type": "sale",
        "status": "active",
        "list_price": 16800000,
        "marketing_title": "Jubilee Hills independent house",
        "marketing_description": "Hyderabad west, gated street, renovation-ready kitchen.",
        "days_published": 7,
    },
    {
        "property_index": 18,
        "tenant_index": 5,
        "listing_type": "rent",
        "status": "active",
        "rent_amount": 45000,
        "marketing_title": "Koregaon Park furnished 2BHK",
        "marketing_description": "Pune central, pet-friendly society, 11-month lease.",
        "days_published": 3,
    },
    {
        "property_index": 19,
        "tenant_index": 4,
        "listing_type": "sale",
        "status": "active",
        "list_price": 9800000,
        "marketing_title": "HSR Layout 2BHK ready to move",
        "marketing_description": "Near metro corridor, vaastu compliant, OC available.",
        "days_published": 6,
    },
]

# client_index / listing_index / staff_index reference combined lists
US_SHOWINGS: list[dict[str, Any]] = [
    {"client_index": 0, "listing_index": 0, "staff_index": 0, "agent_name": "Alex Rivera", "tenant_index": 0, "days_offset": 1, "hour": 14, "status": "confirmed", "notes": "First-time buyer", "showing_type": "private_tour"},
    {"client_index": 1, "listing_index": 1, "staff_index": 0, "agent_name": "Alex Rivera", "tenant_index": 0, "days_offset": 2, "hour": 11, "status": "confirmed", "notes": "Second showing", "showing_type": "private_tour"},
    {"client_index": 2, "listing_index": 2, "staff_index": 4, "agent_name": "Morgan Chen", "tenant_index": 1, "days_offset": 3, "hour": 16, "status": "confirmed", "notes": "Rental tour", "showing_type": "private_tour"},
    {"client_index": 4, "listing_index": 3, "staff_index": 6, "agent_name": "Casey Brooks", "tenant_index": 2, "days_offset": -2, "hour": 10, "status": "completed", "notes": "Model home visit", "showing_type": "open_house"},
    {"client_index": 5, "listing_index": 5, "staff_index": 0, "agent_name": "Alex Rivera", "tenant_index": 0, "days_offset": 4, "hour": 13, "status": "confirmed", "notes": "Relocating from Chicago", "showing_type": "private_tour"},
    {"client_index": 6, "listing_index": 6, "staff_index": 7, "agent_name": "Taylor Walsh", "tenant_index": 3, "days_offset": 5, "hour": 15, "status": "confirmed", "notes": "Denver move-up buyer", "showing_type": "private_tour"},
    {"client_index": 8, "listing_index": 4, "staff_index": 0, "agent_name": "Alex Rivera", "tenant_index": 0, "days_offset": -1, "hour": 17, "status": "completed", "notes": "Loved the backyard", "showing_type": "private_tour"},
    {"client_index": 9, "listing_index": 7, "staff_index": 7, "agent_name": "Taylor Walsh", "tenant_index": 3, "days_offset": 6, "hour": 10, "status": "confirmed", "notes": "Investor client", "showing_type": "private_tour"},
    {"client_index": 10, "listing_index": 6, "staff_index": 7, "agent_name": "Taylor Walsh", "tenant_index": 3, "days_offset": -3, "hour": 14, "status": "cancelled", "notes": "Client rescheduled", "showing_type": "private_tour"},
]

IN_SHOWINGS: list[dict[str, Any]] = [
    {"client_index": 12, "listing_index": 12, "staff_index": 8, "agent_name": "Priya Sharma", "tenant_index": 4, "days_offset": 1, "hour": 11, "status": "confirmed", "notes": "Site visit with family", "showing_type": "private_tour"},
    {"client_index": 13, "listing_index": 13, "staff_index": 8, "agent_name": "Priya Sharma", "tenant_index": 4, "days_offset": 2, "hour": 16, "status": "confirmed", "notes": "NRI buyer video follow-up", "showing_type": "private_tour"},
    {"client_index": 14, "listing_index": 14, "staff_index": 10, "agent_name": "Kavitha Nair", "tenant_index": 5, "days_offset": 3, "hour": 18, "status": "confirmed", "notes": "Evening rental walkthrough", "showing_type": "private_tour"},
    {"client_index": 15, "listing_index": 16, "staff_index": 8, "agent_name": "Priya Sharma", "tenant_index": 4, "days_offset": 4, "hour": 12, "status": "confirmed", "notes": "Gurugram relocation", "showing_type": "private_tour"},
    {"client_index": 16, "listing_index": 17, "staff_index": 8, "agent_name": "Priya Sharma", "tenant_index": 4, "days_offset": -1, "hour": 15, "status": "completed", "notes": "Hyderabad tech corridor", "showing_type": "private_tour"},
    {"client_index": 17, "listing_index": 18, "staff_index": 10, "agent_name": "Kavitha Nair", "tenant_index": 5, "days_offset": 5, "hour": 11, "status": "confirmed", "notes": "Pune furnished rental", "showing_type": "private_tour"},
]

US_LEADS: list[dict[str, Any]] = [
    {"tenant_index": 0, "client_index": 1, "listing_index": 1, "staff_index": 0, "full_name": "Michael Torres", "email": "m.torres@email.com", "phone_number": "+1-503-555-0102", "source": "website", "stage": "showing_scheduled", "segment": "residential"},
    {"tenant_index": 0, "listing_index": 0, "staff_index": 0, "full_name": "Chris Anderson", "email": "chris.anderson@email.com", "source": "zillow", "stage": "new", "segment": "residential"},
    {"tenant_index": 1, "client_index": 2, "listing_index": 2, "staff_index": 4, "full_name": "Emily Nguyen", "email": "emily.nguyen@email.com", "source": "apartments.com", "stage": "tour_scheduled", "segment": "pm"},
    {"tenant_index": 0, "listing_index": 4, "staff_index": 0, "full_name": "Tyler Brooks", "email": "tyler.brooks@email.com", "phone_number": "+1-512-555-0201", "source": "realtor.com", "stage": "contacted", "segment": "residential"},
    {"tenant_index": 3, "listing_index": 6, "staff_index": 7, "full_name": "Olivia Martinez", "email": "olivia.martinez@email.com", "source": "website", "stage": "qualified", "segment": "residential"},
    {"tenant_index": 0, "listing_index": 5, "staff_index": 0, "full_name": "Kevin Tran", "email": "kevin.tran@email.com", "source": "open_house", "stage": "showing_completed", "segment": "residential"},
]

IN_LEADS: list[dict[str, Any]] = [
    {"tenant_index": 4, "client_index": 12, "listing_index": 12, "staff_index": 8, "full_name": "Ananya Iyer", "email": "ananya.iyer@gmail.com", "phone_number": "+91-98765-43210", "source": "99acres", "stage": "showing_scheduled", "segment": "residential"},
    {"tenant_index": 4, "listing_index": 13, "staff_index": 8, "full_name": "Sanjay Gupta", "email": "sanjay.gupta@gmail.com", "phone_number": "+91-98100-44556", "source": "magicbricks", "stage": "new", "segment": "residential"},
    {"tenant_index": 5, "client_index": 14, "listing_index": 14, "staff_index": 10, "full_name": "Neha Kapoor", "email": "neha.kapoor@gmail.com", "source": "nobroker", "stage": "tour_scheduled", "segment": "pm"},
    {"tenant_index": 4, "listing_index": 16, "staff_index": 9, "full_name": "Deepak Verma", "email": "deepak.verma@gmail.com", "phone_number": "+91-98710-99887", "source": "housing.com", "stage": "contacted", "segment": "residential"},
]

US_KB_ARTICLES: list[dict[str, Any]] = [
    {"tenant_index": 0, "title": "Buyer Process Overview", "content": "Learn the steps from pre-approval to closing. Your agent will guide showings, offers, and inspections."},
    {"tenant_index": 0, "title": "Scheduling a Showing", "content": "Book a private tour through the client portal or ask the assistant for available times."},
    {"tenant_index": 0, "title": "Fair Housing Policy", "content": "We do not discriminate based on race, color, religion, sex, disability, familial status, or national origin."},
    {"tenant_index": 1, "title": "Rental Application Checklist", "content": "Bring photo ID, proof of income, and references. Application fee may apply."},
    {"tenant_index": 1, "title": "Pet Policy — River View", "content": "Cats and dogs under 50 lbs welcome with deposit. Breed restrictions apply per building policy."},
    {"tenant_index": 2, "title": "New Construction Incentives", "content": "Summit Ridge Phase 2 includes closing cost credits for contracts signed before month end."},
    {"tenant_index": 0, "title": "HOA Documents Explained", "content": "Review CC&Rs, budget, and meeting minutes before waiving contingencies."},
    {"tenant_index": 3, "title": "First-Time Buyer Programs", "content": "Colorado and North Carolina down-payment assistance may apply — ask your lender."},
]

IN_KB_ARTICLES: list[dict[str, Any]] = [
    {"tenant_index": 4, "title": "RERA Registration Checklist", "content": "Verify project RERA ID on the state portal before paying a booking amount."},
    {"tenant_index": 4, "title": "Home Loan Pre-Approval in India", "content": "Salaried buyers typically need 3 months payslips, Form 16, and bank statements."},
    {"tenant_index": 4, "title": "Stamp Duty — Karnataka", "content": "Budget for stamp duty and registration charges in addition to the agreement value."},
    {"tenant_index": 5, "title": "Leave and License Basics", "content": "Mumbai rentals commonly use 11-month agreements registered with local authority."},
    {"tenant_index": 5, "title": "Society Maintenance Charges", "content": "Ask for last 6 months maintenance invoices and society NOC before signing."},
    {"tenant_index": 4, "title": "NRI Property Purchase Guide", "content": "NRI buyers may need repatriation certificates — coordinate with your CA and banker."},
]

CONVERSATION_SEEDS: list[dict[str, Any]] = [
    {"session_id": "conv-001", "tenant_index": 0, "client_index": 0, "prompt": "When is my next showing?", "response": "Your next confirmed tour is tomorrow with Alex Rivera at the Oak Street listing."},
    {"session_id": "conv-002", "tenant_index": 0, "listing_index": 0, "prompt": "Tell me about schools near this listing", "response": "I can share general school district links — your agent can discuss fit under fair housing guidelines."},
    {"session_id": "conv-003", "tenant_index": 1, "client_index": 2, "prompt": "Is the river-view condo pet friendly?", "response": "Yes — the building allows cats and dogs under 50 lbs with an additional deposit."},
    {"session_id": "conv-004", "tenant_index": 4, "client_index": 12, "prompt": "What is the stamp duty for Koramangala?", "response": "Stamp duty in Karnataka varies by property value — your agent will share the latest schedule."},
    {"session_id": "conv-005", "tenant_index": 5, "client_index": 14, "prompt": "Can I visit the Powai flat this weekend?", "response": "Kavitha can confirm Saturday evening slots — check Showings in the portal."},
    {"session_id": "conv-006", "tenant_index": 0, "client_index": 5, "prompt": "Compare Capitol Hill and Queen Anne commute times", "response": "Both neighborhoods have strong transit — browse listings and schedule tours for each area."},
]
